import { TaskStatus, TaskPriority, TaskStepStatus, type Task } from "./types";

const now = new Date();
const daysFromNow = (d: number) =>
  new Date(now.getTime() + d * 86400000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 86400000).toISOString();

export const MOCK_TASKS: Task[] = [
  // ── To Do ──
  {
    id: "1",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
    dueBy: daysFromNow(7),
    title: "Notify beneficiaries of estate proceedings",
    description:
      "Send formal notifications to all listed beneficiaries regarding the probate process.",
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
    jobKey: "TASK-001",
    executor: "alice@example.com",
    reviewer: "bob@example.com",
    estate: {
      id: "estate-1",
      deceased: { firstName: "John", lastName: "Doe" },
    },
    steps: [
      { id: "s1", order: 1, status: TaskStepStatus.Completed, title: "Draft notification letter" },
      { id: "s2", order: 2, status: TaskStepStatus.Todo, title: "Send to beneficiaries" },
      { id: "s3", order: 3, status: TaskStepStatus.Todo, title: "Confirm receipt" },
    ],
    _count: { conversations: 3 },
  },
  {
    id: "2",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
    dueBy: daysFromNow(1),
    title: "File inventory and appraisal with court",
    description: "Complete asset inventory and file with probate court.",
    status: TaskStatus.Todo,
    priority: TaskPriority.Important,
    jobKey: "TASK-002",
    executor: "carol@example.com",
    reviewer: null,
    estate: {
      id: "estate-2",
      deceased: { firstName: "Margaret", lastName: "Smith" },
    },
    steps: [
      { id: "s4", order: 1, status: TaskStepStatus.Completed, title: "Compile asset list" },
      { id: "s5", order: 2, status: TaskStepStatus.Completed, title: "Get appraisals" },
      { id: "s6", order: 3, status: TaskStepStatus.Todo, title: "File with court" },
    ],
    _count: { conversations: 1 },
  },
  {
    id: "3",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
    dueBy: null,
    title: "Secure physical property access",
    description: "Change locks and secure all physical estate properties.",
    status: TaskStatus.Blocked,
    priority: TaskPriority.Medium,
    jobKey: "TASK-003",
    executor: "Agent-Secure",
    reviewer: null,
    estate: {
      id: "estate-1",
      deceased: { firstName: "John", lastName: "Doe" },
    },
    steps: [],
    _count: { conversations: 0 },
  },
  {
    id: "4",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(3),
    dueBy: daysAgo(1),
    title: "Submit death certificates to financial institutions",
    description: null,
    status: TaskStatus.Failed,
    priority: TaskPriority.High,
    jobKey: "TASK-004",
    executor: "alice@example.com",
    reviewer: "carol@example.com",
    estate: {
      id: "estate-3",
      deceased: { firstName: "Robert", lastName: "Chen" },
    },
    steps: [
      { id: "s7", order: 1, status: TaskStepStatus.Completed, title: "Order certified copies" },
      { id: "s8", order: 2, status: TaskStepStatus.Todo, title: "Send to each institution" },
    ],
    _count: { conversations: 5 },
  },

  // ── In Progress ──
  {
    id: "5",
    createdAt: daysAgo(14),
    updatedAt: daysAgo(0),
    dueBy: daysFromNow(3),
    title: "Prepare federal estate tax return (Form 706)",
    description: "Compile all financial data and prepare the federal estate tax return.",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Important,
    jobKey: "TASK-005",
    executor: "bob@example.com",
    reviewer: "alice@example.com",
    estate: {
      id: "estate-2",
      deceased: { firstName: "Margaret", lastName: "Smith" },
    },
    steps: [
      { id: "s9", order: 1, status: TaskStepStatus.Completed, title: "Gather financial records" },
      { id: "s10", order: 2, status: TaskStepStatus.InProgress, title: "Calculate gross estate" },
      { id: "s11", order: 3, status: TaskStepStatus.Todo, title: "Complete Form 706" },
      { id: "s12", order: 4, status: TaskStepStatus.Todo, title: "File with IRS" },
    ],
    _count: { conversations: 8 },
  },
  {
    id: "6",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(1),
    dueBy: daysFromNow(14),
    title: "Transfer vehicle titles to beneficiaries",
    description: "Process DMV paperwork for 3 vehicles in the estate.",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
    jobKey: "TASK-006",
    executor: "carol@example.com",
    reviewer: null,
    estate: {
      id: "estate-1",
      deceased: { firstName: "John", lastName: "Doe" },
    },
    steps: [
      { id: "s13", order: 1, status: TaskStepStatus.Completed, title: "Obtain title documents" },
      { id: "s14", order: 2, status: TaskStepStatus.InProgress, title: "Complete transfer forms" },
      { id: "s15", order: 3, status: TaskStepStatus.Todo, title: "Submit to DMV" },
    ],
    _count: { conversations: 2 },
  },
  {
    id: "7",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(0),
    dueBy: daysFromNow(5),
    title: "Close credit card accounts",
    description: "Contact issuers and close all credit card accounts held by the deceased.",
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
    jobKey: "TASK-007",
    executor: "Agent-Finance",
    reviewer: "bob@example.com",
    estate: {
      id: "estate-3",
      deceased: { firstName: "Robert", lastName: "Chen" },
    },
    steps: [
      { id: "s16", order: 1, status: TaskStepStatus.Completed, title: "List all accounts" },
      { id: "s17", order: 2, status: TaskStepStatus.InProgress, title: "Contact issuers" },
      { id: "s18", order: 3, status: TaskStepStatus.Todo, title: "Confirm closures" },
    ],
    _count: { conversations: 0 },
  },

  // ── Awaiting Review ──
  {
    id: "8",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
    dueBy: daysFromNow(10),
    title: "Draft final accounting for court",
    description: "Prepare the final estate accounting showing all income, expenses, and distributions.",
    status: TaskStatus.ReadyForReview,
    priority: TaskPriority.High,
    jobKey: "TASK-008",
    executor: "alice@example.com",
    reviewer: "bob@example.com",
    estate: {
      id: "estate-4",
      deceased: { firstName: "Eleanor", lastName: "Vance" },
    },
    steps: [
      { id: "s19", order: 1, status: TaskStepStatus.Completed, title: "Compile transactions" },
      { id: "s20", order: 2, status: TaskStepStatus.Completed, title: "Reconcile accounts" },
      { id: "s21", order: 3, status: TaskStepStatus.Completed, title: "Draft report" },
      { id: "s22", order: 4, status: TaskStepStatus.Todo, title: "File with court" },
    ],
    _count: { conversations: 4 },
  },
  {
    id: "9",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(1),
    dueBy: null,
    title: "Review real property transfer deed",
    description: null,
    status: TaskStatus.InReview,
    priority: TaskPriority.Medium,
    jobKey: "TASK-009",
    executor: "bob@example.com",
    reviewer: "carol@example.com",
    estate: {
      id: "estate-1",
      deceased: { firstName: "John", lastName: "Doe" },
    },
    steps: [
      { id: "s23", order: 1, status: TaskStepStatus.Completed, title: "Draft deed" },
      { id: "s24", order: 2, status: TaskStepStatus.Completed, title: "Legal review" },
    ],
    _count: { conversations: 6 },
  },
  {
    id: "10",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(0),
    dueBy: daysFromNow(2),
    title: "Verify life insurance claim submissions",
    description: "Confirm all life insurance claims have been properly filed and are being processed.",
    status: TaskStatus.ReviewComplete,
    priority: TaskPriority.Low,
    jobKey: "TASK-010",
    executor: "carol@example.com",
    reviewer: "alice@example.com",
    estate: {
      id: "estate-2",
      deceased: { firstName: "Margaret", lastName: "Smith" },
    },
    steps: [
      { id: "s25", order: 1, status: TaskStepStatus.Completed, title: "Identify policies" },
      { id: "s26", order: 2, status: TaskStepStatus.Completed, title: "File claims" },
      { id: "s27", order: 3, status: TaskStepStatus.Completed, title: "Track processing" },
    ],
    _count: { conversations: 1 },
  },

  // ── Completed ──
  {
    id: "11",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
    dueBy: daysAgo(7),
    title: "Obtain letters testamentary",
    description: "File petition and obtain letters testamentary from probate court.",
    status: TaskStatus.Completed,
    priority: TaskPriority.Important,
    jobKey: "TASK-011",
    executor: "alice@example.com",
    reviewer: null,
    estate: {
      id: "estate-1",
      deceased: { firstName: "John", lastName: "Doe" },
    },
    steps: [
      { id: "s28", order: 1, status: TaskStepStatus.Completed, title: "File petition" },
      { id: "s29", order: 2, status: TaskStepStatus.Completed, title: "Attend hearing" },
      { id: "s30", order: 3, status: TaskStepStatus.Completed, title: "Receive letters" },
    ],
    _count: { conversations: 2 },
  },
  {
    id: "12",
    createdAt: daysAgo(25),
    updatedAt: daysAgo(10),
    dueBy: null,
    title: "Cancel utilities and subscriptions",
    description: "Cancel all recurring services in the name of the deceased.",
    status: TaskStatus.Completed,
    priority: TaskPriority.Low,
    jobKey: "TASK-012",
    executor: "Agent-Admin",
    reviewer: null,
    estate: {
      id: "estate-3",
      deceased: { firstName: "Robert", lastName: "Chen" },
    },
    steps: [
      { id: "s31", order: 1, status: TaskStepStatus.Completed, title: "List subscriptions" },
      { id: "s32", order: 2, status: TaskStepStatus.Completed, title: "Cancel each service" },
    ],
    _count: { conversations: 0 },
  },
  {
    id: "13",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(4),
    dueBy: daysAgo(2),
    title: "Publish notice to creditors in local newspaper",
    description: null,
    status: TaskStatus.Completed,
    priority: TaskPriority.Medium,
    jobKey: "TASK-013",
    executor: "bob@example.com",
    reviewer: "alice@example.com",
    estate: {
      id: "estate-4",
      deceased: { firstName: "Eleanor", lastName: "Vance" },
    },
    steps: [],
    _count: { conversations: 3 },
  },

  // ── Extra tasks for density ──
  {
    id: "14",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(0),
    dueBy: daysFromNow(0),
    title: "Respond to creditor claim from First National Bank",
    description: "Review and formally respond to the creditor claim filed by First National Bank.",
    status: TaskStatus.Todo,
    priority: TaskPriority.Important,
    jobKey: "TASK-014",
    executor: "alice@example.com",
    reviewer: "bob@example.com",
    estate: {
      id: "estate-4",
      deceased: { firstName: "Eleanor", lastName: "Vance" },
    },
    steps: [
      { id: "s33", order: 1, status: TaskStepStatus.Todo, title: "Review claim details" },
      { id: "s34", order: 2, status: TaskStepStatus.Todo, title: "Draft response" },
      { id: "s35", order: 3, status: TaskStepStatus.Todo, title: "File with court" },
    ],
    _count: { conversations: 7 },
  },
  {
    id: "15",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
    dueBy: daysFromNow(21),
    title: "Distribute personal property per will terms",
    description: "Coordinate distribution of personal effects to named beneficiaries.",
    status: TaskStatus.InProgress,
    priority: null,
    jobKey: "TASK-015",
    executor: "carol@example.com",
    reviewer: null,
    estate: {
      id: "estate-2",
      deceased: { firstName: "Margaret", lastName: "Smith" },
    },
    steps: [
      { id: "s36", order: 1, status: TaskStepStatus.Completed, title: "Catalog items" },
      { id: "s37", order: 2, status: TaskStepStatus.Todo, title: "Contact beneficiaries" },
      { id: "s38", order: 3, status: TaskStepStatus.Todo, title: "Arrange delivery" },
    ],
    _count: { conversations: 0 },
  },
  {
    id: "16",
    createdAt: daysAgo(9),
    updatedAt: daysAgo(1),
    dueBy: daysFromNow(4),
    title: "Obtain EIN for estate trust",
    description: "Apply for an Employer Identification Number for the estate trust account.",
    status: TaskStatus.ReadyForReview,
    priority: TaskPriority.High,
    jobKey: "TASK-016",
    executor: "Agent-Tax",
    reviewer: "alice@example.com",
    estate: {
      id: "estate-3",
      deceased: { firstName: "Robert", lastName: "Chen" },
    },
    steps: [
      { id: "s39", order: 1, status: TaskStepStatus.Completed, title: "Prepare SS-4 form" },
      { id: "s40", order: 2, status: TaskStepStatus.Completed, title: "Submit to IRS" },
    ],
    _count: { conversations: 1 },
  },
];

export const MOCK_ESTATES = [
  { id: "estate-1", name: "John Doe" },
  { id: "estate-2", name: "Margaret Smith" },
  { id: "estate-3", name: "Robert Chen" },
  { id: "estate-4", name: "Eleanor Vance" },
];
